### ISSUE TITLE
The directory name is invalid.

### ISSUE THREAD

**Issue by miaadev** [cmkushnir/NMSModBuilder#12]
```
[12:58:43.753] System.ArgumentException: The directory name  is invalid. (Parameter 'path')
   at System.IO.FileSystemWatcher.CheckPathValidity(String path)
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at cmk.NMS.Game.MODS.Files..ctor(Data GAME, Identifier LANGUAGE_ID)
   at cmk.NMS.Game.Data..ctor(Data LOCATION, Identifier LANGUAGE_ID)
   at cmk.NMS.Game.Data.<>c__DisplayClass41_0.<CreateAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at cmk.NMS.Game.Data.CreateAsync(Data LOCATION)
   at cmk.NMS.Game.Data.SelectAsync()
   at cmk.NMS.Game.Location.Buttons.ButtonClick(ImageButton SENDER)
```

**Comment by cmkushnir** [comment]
See: [Discord - No Man's Sky Modding - nmsmb-csharp](https://discord.com/channels/215514623384748034/891984842869313536/1129605259233329232)
You likely don't have a MODS folder in your PCBANKS folder.  NMSMB should have given a more specific error, both in the tooltip for the game icon you clicked, and at the top of the log when it first started loading the game data.
