### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by erdeminofff** [cmkushnir/NMSModBuilder#9]
Toggle_Pak_Format can convert PC Pak files to HGPak files without issue. But when converting HGPak files to PC Pak files it gives the following error:

[05:29:07.705] Compiled Toggle_Pak_Format => Assembly cmk_Query_Toggle_Pak_Format
[05:29:12.866] AssemblyLoadContext cmk_Query_Toggle_Pak_Format_4057546 loaded cmk_Util
[05:29:12.881] AssemblyLoadContext cmk_Query_Toggle_Pak_Format_4057546 loaded cmk_Query_Toggle_Pak_Format
[05:29:30.847] Checking cache for unedited items ...
[05:29:30.888] MODELS/PLANETS/COMMON/SHRUBS/CLIFFSHRUB.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.888] MODELS/PLANETS/COMMON/FLAGS/MARTIANFLAG01.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.888] MODELS/PLANETS/COMMON/SHRUBS/WEED02.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.889] MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP01.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.889] MODELS/PLANETS/COMMON/BUILDINGS/ROBOT/PARTS/SCRAPWHEELBARROW.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.889] MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP08.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.889] MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP05.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.908] MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP05.GEOMETRY.MBIN.MACOS
[05:29:30.908] MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP01.GEOMETRY.MBIN.MACOS
[05:29:30.908] MODELS/PLANETS/COMMON/SHRUBS/WEED02.GEOMETRY.MBIN.MACOS
[05:29:30.908] MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP06.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.908] MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP02.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.909] MODELS/PLANETS/COMMON/FLAGS/MARTIANFLAG01.GEOMETRY.MBIN.MACOS
[05:29:30.909] MODELS/PLANETS/COMMON/SHRUBS/WEED03.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.909] MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP06.GEOMETRY.MBIN.MACOS
[05:29:30.909] MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP07.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.909] MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP02.GEOMETRY.MBIN.MACOS
[05:29:30.910] MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP08.GEOMETRY.MBIN.MACOS
[05:29:30.910] MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP04.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.911] MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP04.GEOMETRY.MBIN.MACOS
[05:29:30.911] MODELS/PLANETS/COMMON/SHRUBS/GRASSCLUMP07.GEOMETRY.MBIN.MACOS
[05:29:30.924] MODELS/PLANETS/COMMON/BUILDINGS/ROBOT/PARTS/SCRAPWHEELBARROW.GEOMETRY.MBIN.MACOS
[05:29:30.924] MODELS/PLANETS/COMMON/FLAGS/MARTIANFLAG02.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.926] MODELS/PLANETS/COMMON/BUILDINGS/ROBOT/ROBOTBASE.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.939] MODELS/PLANETS/COMMON/SHRUBS/WEED03.GEOMETRY.MBIN.MACOS
[05:29:30.939] MODELS/PLANETS/COMMON/SHRUBS/SHRUB01.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.940] MODELS/PLANETS/COMMON/SHRUBS/WEED04.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.951] MODELS/PLANETS/COMMON/SHRUBS/CLIFFSHRUB.GEOMETRY.MBIN.MACOS
[05:29:30.954] MODELS/PLANETS/COMMON/SHRUBS/FERN01.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.954] MODELS/PLANETS/COMMON/FLAGS/MARTIANFLAG02.GEOMETRY.MBIN.MACOS
[05:29:30.955] MODELS/PLANETS/COMMON/FLAGS/MARTIANFLAG03.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.969] MODELS/PLANETS/COMMON/SHRUBS/WEED04.GEOMETRY.MBIN.MACOS
[05:29:30.981] MODELS/PLANETS/COMMON/FLAGS/MARTIANFLAG03.GEOMETRY.MBIN.MACOS
[05:29:30.981] MODELS/PLANETS/COMMON/BUILDINGS/ROBOT/PARTS/SILOLOOSECLOTH.GEOMETRY.DATA.MBIN.MACOS
[05:29:30.982] MODELS/PLANETS/COMMON/SHRUBS/FERN01.GEOMETRY.MBIN.MACOS
[05:29:30.993] MODELS/PLANETS/COMMON/SHRUBS/FERN02.GEOMETRY.DATA.MBIN.MACOS
[05:29:31.008] MODELS/PLANETS/COMMON/SHRUBS/FERN02.GEOMETRY.MBIN.MACOS
[05:29:31.022] MODELS/PLANETS/COMMON/SHRUBS/SHRUB01.GEOMETRY.MBIN.MACOS
[05:29:31.022] MODELS/PLANETS/COMMON/SHRUBS/WEED01.GEOMETRY.DATA.MBIN.MACOS
[05:29:31.023] MODELS/PLANETS/COMMON/SHRUBS/WEED01.GEOMETRY.MBIN.MACOS
[05:29:31.035] MODELS/PLANETS/COMMON/BUILDINGS/ROBOT/PARTS/STATIONCORESTAND.GEOMETRY.MBIN.MACOS
[05:29:31.072] MODELS/PLANETS/COMMON/BUILDINGS/ROBOT/PARTS/SILOLOOSECLOTH.GEOMETRY.MBIN.MACOS
[05:29:31.077] MODELS/PLANETS/COMMON/BUILDINGS/ROBOT/PARTS/STATIONCORESTAND.GEOMETRY.DATA.MBIN.MACOS
[05:29:31.209] MODELS/PLANETS/COMMON/BUILDINGS/ROBOT/ROBOTBASE.GEOMETRY.MBIN.MACOS
[05:29:31.220] MODELS/PLANETS/COMMON/BUILDINGS/ROBOT/PARTS/ROBOTMULTITOOLCRATE.GEOMETRY.DATA.MBIN.MACOS
[05:29:31.225] MODELS/PLANETS/COMMON/BUILDINGS/ROBOT/PARTS/ROBOTMULTITOOLCRATE.GEOMETRY.MBIN.MACOS
[05:29:31.256] MODELS/PLANETS/COMMON/BUILDINGS/ROBOT/PARTS/ROBOTTERMINAL.GEOMETRY.DATA.MBIN.MACOS
[05:29:31.413] MODELS/PLANETS/COMMON/BUILDINGS/ROBOT/PARTS/ROBOTTERMINAL.GEOMETRY.MBIN.MACOS
[05:29:31.413] Compressing edited items ...
[05:29:31.414] Building pak stream ...
[05:29:31.431] System.NullReferenceException: Object reference not set to an instance of an object.
   at Toggle_Pak_Format.Execute() in .\Scripts\Query\Toggle_Pak_Format.cs:line 33
   at cmk.NMS.Script.Class.Execute(Data GAME, Log LOG, CancellationToken CANCEL)
[05:29:32.235] AssemblyLoadContext cmk_Query_Toggle_Pak_Format_4057546 unloaded

It gives the same error even though I tried with different pak files of the game. Also different version of libMBINs did not solve the problem.

**Comment by cmkushnir** [comment]
It's an error in the script.  Actually both ways should have failed as no items were edited.
```
			var data = info.ExtractData(Log);
			data.IsEdited = true;    <=== add this line to script (without this comment)
```
That will force each extracted item to be treated as if it is edited.  Only items marked as IsEdited should be added to a pak when being built.  The HGPAK build code doesn't have this check (bug), but the PSARC build code does.

The next release will add the IsEdited check to the HGPAK build code, and add data.IsEdited = true to the script.
